### ISSUE TITLE
Unable to load N64 ROMs

### ISSUE THREAD

**Issue by circuit-static** [free5ty1e/primestationone#67]
When attempting to launch at least 3 different N64 ROMs, I got another error that was not on screen long enough to read, but it appears it could not find files needed as I was unable to load the 3 games I tried in N64 emulation.

I can't recall if I tried these before I turned on Netplay, I will try again with it turned off just to make sure it isn't part of the problem, but that will be later. Just wanted to let you know what I saw this morning

**Comment by free5ty1e** [comment]
I'm not certain the N64 emulator is baked into the base RetroPie 2.5 beta image that I started with; I'll have to try on a fresh image and see if this is the issue.  Other than actually having the n64-libretrocore emulator built and installed on the system, the only other thing I can think of is type `sudo raspi-config` and change your memory split so that the GPU has 128MB (leaving the majority of the 512MB for the CPU to utilize; the N64 emulator wants at least 384MB of CPU memory to run correctly)

**Comment by free5ty1e** [comment]
V0.9997 fixes this.
